"""导入全部模型，确保它们注册到 Base.metadata。"""

from app.db.counters import NumberCounter
from app.modules.ai.models import (
    AiAnswerCache,
    AiDecision,
    AiEvalRun,
    AiMessageFeedback,
    AiSessionState,
    AiSettings,
    AiSuggestion,
    CopilotAlert,
    LlmCall,
    SessionSummary,
)
from app.modules.audit.models import AuditLog
from app.modules.billing.models import Invoice, Plan, Subscription
from app.modules.channels.models import ChannelAccount
from app.modules.conversation.models import (
    ChatSession,
    ImOp,
    Message,
    Room,
    SessionEvent,
    SessionTransfer,
    SessionWatcher,
)
from app.modules.customer.models import (
    Customer,
    CustomerIdentity,
    CustomerLeadDraft,
    CustomerOwnerHistory,
    CustomerTransferRequest,
)
from app.modules.iam.models import RefreshToken, Role, Staff, StaffRole
from app.modules.kb.models import (
    KbCandidate,
    KbCategory,
    KbChunk,
    KbDigest,
    KbExtraction,
    KbFeedback,
    KbImportJob,
    KbItem,
    KbItemVersion,
    KbRead,
    KbSpace,
)
from app.modules.lifecycle.models import SupportGrant, TenantDeletion, TenantExport
from app.modules.notifications.models import StaffNotification
from app.modules.platform.models import LlmProvider, PlatformSetting, PromptTemplate
from app.modules.quickreply.models import QuickReply
from app.modules.routing.models import AgentState, RoutingPolicy, SkillGroup, SkillGroupMember
from app.modules.security.models import FileScan, PrivacyRequest, TenantKey, TenantSetting
from app.modules.tenancy.models import PlatformUser, Tenant
from app.modules.todos.models import Todo, TodoEvent, TodoExtraction, TodoType
from app.modules.usage.models import UsageDaily
from app.modules.wecom.models import (
    WecomBroadcast,
    WecomBroadcastResult,
    WecomContactFollow,
    WecomCorp,
    WecomGroupChat,
    WecomGroupMember,
    WecomGroupTransfer,
    WecomJoinWay,
    WecomKfAccount,
    WecomMember,
    WecomSidebarMessage,
    WecomTag,
    WecomTransfer,
    WecomZoneResult,
)

__all__ = [
    "AgentState",
    "AiAnswerCache",
    "AiDecision",
    "AiEvalRun",
    "AiMessageFeedback",
    "AiSessionState",
    "AiSettings",
    "AiSuggestion",
    "AuditLog",
    "ChannelAccount",
    "ChatSession",
    "CopilotAlert",
    "Customer",
    "CustomerIdentity",
    "CustomerLeadDraft",
    "CustomerOwnerHistory",
    "CustomerTransferRequest",
    "FileScan",
    "ImOp",
    "Invoice",
    "KbCandidate",
    "KbCategory",
    "KbChunk",
    "KbDigest",
    "KbExtraction",
    "KbFeedback",
    "KbImportJob",
    "KbItem",
    "KbItemVersion",
    "KbRead",
    "KbSpace",
    "LlmCall",
    "LlmProvider",
    "Message",
    "NumberCounter",
    "Plan",
    "PlatformSetting",
    "PlatformUser",
    "PrivacyRequest",
    "PromptTemplate",
    "QuickReply",
    "RefreshToken",
    "Role",
    "Room",
    "RoutingPolicy",
    "SessionEvent",
    "SessionSummary",
    "SessionTransfer",
    "SessionWatcher",
    "SkillGroup",
    "SkillGroupMember",
    "Staff",
    "StaffNotification",
    "StaffRole",
    "Subscription",
    "SupportGrant",
    "Tenant",
    "TenantDeletion",
    "TenantExport",
    "TenantKey",
    "TenantSetting",
    "Todo",
    "TodoEvent",
    "TodoExtraction",
    "TodoType",
    "UsageDaily",
    "WecomBroadcast",
    "WecomBroadcastResult",
    "WecomContactFollow",
    "WecomCorp",
    "WecomGroupChat",
    "WecomGroupMember",
    "WecomGroupTransfer",
    "WecomJoinWay",
    "WecomKfAccount",
    "WecomMember",
    "WecomSidebarMessage",
    "WecomTag",
    "WecomTransfer",
    "WecomZoneResult",
]
