import {
  AlarmClock,
  Avatar,
  Box,
  ChatDotRound,
  ChatLineRound,
  Clock,
  Coin,
  Connection,
  DataLine,
  Document,
  Finished,
  FolderOpened,
  Goods,
  HomeFilled,
  MagicStick,
  Money,
  OfficeBuilding,
  Opportunity,
  Promotion,
  Reading,
  Setting,
  ShoppingCart,
  Stamp,
  Tickets,
  TrendCharts,
  User,
} from '@element-plus/icons-vue'
import type { Component } from 'vue'

import type { MenuIcon } from './menu'

/** 菜单图标（左侧菜单和分配权限时的业务模块共用）。 */
export const MENU_ICONS: Record<MenuIcon, Component> = {
  home: HomeFilled,
  chat: ChatDotRound,
  history: Clock,
  ticket: Tickets,
  task: Finished,
  order: ShoppingCart,
  goods: Goods,
  money: Money,
  contract: Stamp,
  material: FolderOpened,
  production: Box,
  warehouse: OfficeBuilding,
  user: User,
  opportunity: Opportunity,
  reading: Reading,
  ai: MagicStick,
  wake: AlarmClock,
  assistant: ChatLineRound,
  avatar: Avatar,
  chart: DataLine,
  profit: TrendCharts,
  tokens: Coin,
  integration: Connection,
  broadcast: Promotion,
  audit: Document,
  setting: Setting,
}
